version: '3.1'
services:
  todo-app:
    container_name: todo-app
    image: mhmtmrtyzc/todo-app
    ports:
      - "8099:8099"
    depends_on:
      - postgresqldb

  postgresqldb:
    container_name: postgresqldb
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=1
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
